# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: CC0-1.0

blank_issues_enabled: false
contact_links:
  - name: Discussion
    url: https://github.com/teamtype/teamtype/discussions
    about: Ask a question or discuss something
